export const DEFAULT_SCHEMA = [
  'Id',
  'Symbol',
  'Name',
  'Image',
  'Current Price',
  'Market Cap',
  'Market Cap Rank',
  'Fully Diluted Valuation',
  'Total Volume',
  'High 24h',
  'Low 24h',
  'Price Change 24h',
  'Price Change Percentage 24h',
  'Market Cap Change 24h',
  'Market Cap Change Percentage 24h',
  'Circulating Supply',
  'Total Supply',
  'Max Supply',
  'Ath',
  'Ath Change Percentage',
  'Ath Date',
  'Atl',
  'Atl Change Percentage',
  'Atl Date',
  'Roi',
  'Last Updated',
  'Price Change Percentage 1h In Currency',
  'Price Change Percentage 24h In Currency',
  'Price Change Percentage 30d In Currency',
  'Price Change Percentage 7d In Currency',
  'Roi Times',
  'Roi Currency',
  'Roi Percentage',
];
